name: CI Test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Run bat file 1
      shell: cmd
      run: "..\\..\\compileTestMe.bat"
    - name: Run bat file 2
      shell: cmd
      run: ".\compileTestMe.bat"


    #- name: Build
      #run: dotnet build --no-restore

    #- name: Test
      #run: dotnet test --no-build --verbosity normal